name: 功能需求
description: 提交新功能或改进建议
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请尽量说明使用场景与期望效果。
  - type: textarea
    id: background
    attributes:
      label: 需求背景
      description: 说明为什么需要该功能
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 你的建议实现方式或交互
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 补充说明
    validations:
      required: false
